### ISSUE TITLE
底部刷新问题

### ISSUE THREAD

**Issue by DCoderSea** [Werb/MoreType#4]
在底部刷新数据之后，在用SwipeRefrshLayout 刷新之后，有时候底部无法刷新

**Comment by werbhelius** [comment]
@ater695943820 无法刷新是指什么？ 上滑加载是依赖 recyclerView 的 OnScrollListener 构建的，按理来说 下拉刷新 和 上滑加载 是独立存在的，二者之间没有联系。

**Comment by ater695943820** [comment]
就是下方无法加入footer并且滑动监听好像也监听不到，还有点击事件照着demo写的还是没有监听是什么原因？

**Comment by DCoderSea** [comment]
有时候上方刷新完，在上拉加载下方无法加入footer并且滑动监听好像也监听不到，不是每次都会出现这种情况。

**Comment by werbhelius** [comment]
@ater695943820 footer 和 数据都没有加载出来吗？

**Comment by DCoderSea** [comment]
我发现在数据加载失败的时候，底部的footer就再也滑不出来了，除非在刷新一下，就可以了。
