### ISSUE TITLE
更改视图绑定的方法

### ISSUE THREAD

**Issue by wenjiahui** [Werb/MoreType#6]
使用这个库真的好方便.  不过就是想了解一下为什么会有registerItem()这个方法?  需要调用者自己组合布局和绑定操作.  多多少少有点不太方法.  个人觉得应该在MoreViewHolder里声明布局.  调用者就可以清晰知道哪种数据类型对应哪种布局

**Comment by werbhelius** [comment]
@wenjiahui 
#### 先说一下我的想法
最初的想法我也是想在 `MoreViewHolder ` 里实现布局的声明，但没有找到很好的实现方式，所以采用了在外部注册的方式，为了保持 **单一类型注册** 和 **多种类型注册** 的一致性，所以都采用了 `RegisterItem ` 来充当桥梁，如果你有好的实现方式，可以 pull request 或者直接发邮件都可以。

#### 关于组合布局和绑定操作
例如我有一个 `FooterViewHolder` ，但我想要在不同的地方实现不同的样式，那么就可以采用这种组合的方式。

最后这个库仍然在尝试各种可能的方法来实现最优的结果，感谢你的建议。
