### ISSUE TITLE
找不到kotlinx.android.extensions.LayoutContainer的类文件

### ISSUE THREAD

**Issue by zy841336855** [Werb/MoreType#8]
错误: 无法访问LayoutContainer

extends com.werb.library.MoreViewHolder

找不到kotlinx.android.extensions.LayoutContainer的类文件

**Comment by zy841336855** [comment]
000

**Comment by zy841336855** [comment]
public final class MessageOutViewHolder extends com.werb.library.MoreViewHolder

  找不到kotlinx.android.extensions.LayoutContainer的类文件

这个错误，自定义Holder就报这个错误

**Comment by werbhelius** [comment]
LayoutContainer 属于 Kotlin 实验性参数，需要在 Gradle 中开启 ，[例如 app.gradle](https://github.com/werbhelius/MoreType/blob/master/app/build.gradle)
```
androidExtensions {
        experimental = true
}
```
